name: Deploy_to_S3

on:
  create: # Trigger when a new branch is created
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"  # Ensure compatibility with AWS Lambda

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r Data_Extraction/requirements.txt -t .  # Install directly

    - name: Package Lambda Function
      run: |
        zip -r code.zip .  # Zip everything, including dependencies

    - name: Deploy Lambda Function and Set Environment Variable
      run: |
        echo "Deploying Lambda Function on branch: ${{ github.ref_name }}"
        
        aws lambda update-function-code \
          --function-name DataExtraction \
          --zip-file fileb://code.zip
        
        aws lambda update-function-configuration \
          --function-name DataExtraction \
          --environment "Variables={BUCKET_NAME=${{ github.ref_name }}-myproject}"
    
    - name: Wait for Lambda Update
      run: |
        echo "Waiting for Lambda deployment to propagate..."
        sleep 10

    - name: Start Step Function Execution
      run: |
        aws stepfunctions start-execution \
          --state-machine-arn "arn:aws:states:us-east-1:180294214655:stateMachine:MyStateMachine-o02n93kz6" \
          --input '{"Disease": "Alzheimer"}'
       