name: Deploy to S3

on:
  create: # Trigger when a new branch is created
    branches:
      - "*"
  push:
    branches:
      - main
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    # Step 3: Deploy to S3
    - name: Deploy to S3
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9.-')
        if [ "$BRANCH_NAME" = "main" ]; then
          MAIN_BUCKET_NAME="main-bucket-myproject"
          echo "Deploying main branch code to bucket: $MAIN_BUCKET_NAME"
          if aws s3api head-bucket --bucket "$MAIN_BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $MAIN_BUCKET_NAME already exists"
          else
            aws s3api create-bucket --bucket "$MAIN_BUCKET_NAME" --region us-east-1
          fi
          aws s3 sync . s3://$MAIN_BUCKET_NAME --delete
        else
          BUCKET_NAME="${BRANCH_NAME}-myproject"
          echo "Creating bucket: $BUCKET_NAME and deploying branch code"
          if [ "us-east-1" = "us-east-1" ]; then
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1
          else
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1 \
              --create-bucket-configuration LocationConstraint=us-east-1
          fi
          aws s3 sync . s3://$BUCKET_NAME --delete
        fi
