name: Deploy to S3

on:
  push:
    branches:
      - main
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    # Step 3: Deploy based on branch
    - name: Deploy to S3
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9.-')
        if [ "$BRANCH_NAME" = "main" ]; then
          # Deploy to the main bucket
          MAIN_BUCKET_NAME="main-bucket-${{ vars.S3_BUCKET_NAME_PREFIX }}"
          echo "Deploying main branch code to bucket: $MAIN_BUCKET_NAME"
          aws s3 sync . s3://$MAIN_BUCKET_NAME --delete
        else
          # Create a new bucket for the branch
          BUCKET_NAME="${BRANCH_NAME}-${{ vars.S3_BUCKET_NAME_PREFIX }}"
          echo "Creating bucket: $BUCKET_NAME and deploying branch code"
          if [ "${{ vars.AWS_REGION }}" = "us-east-1" ]; then
            # For us-east-1, do not include LocationConstraint
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region ${{ vars.AWS_REGION }}
          else
            # For other regions, include LocationConstraint
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region ${{ vars.AWS_REGION }} \
              --create-bucket-configuration LocationConstraint=${{ vars.AWS_REGION }}
          fi
          # Sync code to the new bucket
          aws s3 sync . s3://$BUCKET_NAME --delete
        fi
